version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Detroit"
    # only allow critical security update PRs
    open-pull-requests-limit: 0
