name: Hot Potato CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  isMaster: ${{ github.ref == 'refs/heads/master' }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Generate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: './GitVersion.yml'

    - name: Display GitVersion outputs
      run: |
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"

    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:	
        dotnet-version: 2.2.x

    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 3.1.x

    - name: Build
      run: |
        dotnet build --configuration Release -p:Version=${{ env.GitVersion_MajorMinorPatch }}

    - name: Run Unit Tests .NET 2.2
      run: |
        dotnet test ./test/HotPotato.Core.Test/HotPotato.Core.Test.csproj -f "netcoreapp2.2" -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=$GITHUB_WORKSPACE/test/coverage/coreCoverage.xml -p:Exclude="[xunit.*]*" -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/coreResults.xml" --no-restore --no-build
        dotnet test ./test/HotPotato.AspNetCore.Middleware.Test/HotPotato.AspNetCore.Middleware.Test.csproj -f "netcoreapp2.2" -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=$GITHUB_WORKSPACE/test/coverage/middlewareCoverage.xml -p:Include="[*.Middleware]*" -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/middlewareResults.xml" --no-restore --no-build
        dotnet test ./test/HotPotato.OpenApi.Test/HotPotato.OpenApi.Test.csproj -f "netcoreapp2.2" -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=$GITHUB_WORKSPACE/test/coverage/openApiCoverage.xml -p:Include="[*.OpenApi]*" -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/openapiResults.xml" --no-restore --no-build

    - name: Run Unit Tests .NET 3.1
      run: |
        dotnet test ./test/HotPotato.Core.Test/HotPotato.Core.Test.csproj -f "netcoreapp3.1" -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=$GITHUB_WORKSPACE/test/coverage/coreCoverage.xml -p:Exclude="[xunit.*]*" -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/coreResults.xml" --no-restore --no-build
        dotnet test ./test/HotPotato.AspNetCore.Middleware.Test/HotPotato.AspNetCore.Middleware.Test.csproj -f "netcoreapp3.1" -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=$GITHUB_WORKSPACE/test/coverage/middlewareCoverage.xml -p:Include="[*.Middleware]*" -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/middlewareResults.xml" --no-restore --no-build
        dotnet test ./test/HotPotato.OpenApi.Test/HotPotato.OpenApi.Test.csproj -f "netcoreapp3.1" -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=$GITHUB_WORKSPACE/test/coverage/openApiCoverage.xml -p:Include="[*.OpenApi]*" -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/openapiResults.xml" --no-restore --no-build

    - name: Run Integration Tests
      run: |
        dotnet test ./test/HotPotato.Integration.Test/HotPotato.Integration.Test.csproj -f "netcoreapp2.2" -c Release -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/integrationResults.xml" --no-restore --no-build
        dotnet test ./test/HotPotato.Integration.Test/HotPotato.Integration.Test.csproj -f "netcoreapp3.1" -c Release -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/integrationResults.xml" --no-restore --no-build

    # Commenting out until we figure out the best way to deal with the hosted spec for these tests
    # - name: Run E2E Tests .NET 2.2
    #   run: |
    #     dotnet test ./test/HotPotato.E2E.Test/HotPotato.E2E.Test.csproj -f "netcoreapp2.2" -c Release -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/E2EResults.xml" --no-restore --no-build
    # - name: Run E2E Tests .NET 3.1
    #   run: |
    #     dotnet test ./test/HotPotato.TestServer.Test/HotPotato.TestServ.Test.csproj -c Release -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/testServerResults.xml" --no-restore --no-build
    #     dotnet test ./test/HotPotato.E2E.Test/HotPotato.E2E.Test.csproj -f "netcoreapp3.1" -c Release -l:"JUnit;LogFilePath=$GITHUB_WORKSPACE/test/results/E2EResults.xml" --no-restore --no-build

    # - name: Start Hot Potato For Postman Tests
    #   run: |
    #     dotnet $GITHUB_WORKSPACE/src/HotPotato.AspNetCore.Host/bin/Release/netcoreapp3.1/HotPotato.AspNetCore.Host.dll &
    #     dotnet $GITHUB_WORKSPACE/test/HotPotato.Api/bin/Release/netcoreapp3.1/HotPotato.Api.dll &
 
    # - name: Run Postman Tests
    #   uses: anthonyvscode/newman-action@v1
    #   with:
    #     collection: ./test/HappyPathTests.postman_collection.json
    #     reporters: cli

    - name: Deploy 
      run: |
        dotnet pack ./src/HotPotato.AspNetCore.Host/HotPotato.AspNetCore.Host.csproj -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch }} -c Release --no-build --no-restore
        dotnet pack ./src/HotPotato.AspNetCore.Middleware/HotPotato.AspNetCore.Middleware.csproj -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch}} -c Release --no-build --no-restore
        dotnet pack ./src/HotPotato.Core/HotPotato.Core.csproj -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch }} -c Release --no-build --no-restore
        dotnet pack ./src/HotPotato.OpenApi/HotPotato.OpenApi.csproj -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch }} -c Release --no-build --no-restore

        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.AspNetCore.Host/**/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/HylandSoftware/index.json --skip-duplicate
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.AspNetCore.Middleware/**/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/HylandSoftware/index.json --skip-duplicate
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.Core/**/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/HylandSoftware/index.json --skip-duplicate
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.OpenApi/**/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/HylandSoftware/index.json --skip-duplicate

    - name: Push Images
      if: contains(github.ref, "refs/heads/v*")
      run: |
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.AspNetCore.Host/**/*.nupkg -k ${{ secrets.TESTAUTOMATION_GITHUB }} -s https://artifactory.onbase.net/artifactory/api/nuget/nuget --skip-duplicate
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.AspNetCore.Middleware/**/*.nupkg -k ${{ secrets.TESTAUTOMATION_GITHUB }} -s https://artifactory.onbase.net/artifactory/api/nuget/nuget --skip-duplicate
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.Core/**/*.nupkg -k ${{ secrets.TESTAUTOMATION_GITHUB }} -s https://artifactory.onbase.net/artifactory/api/nuget/nuget --skip-duplicate
        dotnet nuget push $GITHUB_WORKSPACE/src/HotPotato.OpenApi/**/*.nupkg -k ${{ secrets.TESTAUTOMATION_GITHUB }} -s https://artifactory.onbase.net/artifactory/api/nuget/nuget --skip-duplicate

        docker build --tag hcr.io/automated-testing/hot-potato:${{ env.GitVersion_MajorMinorPatch }} --build-arg IMAGE_VERSION=${{ env.GitVersion_MajorMinorPatch }}
        docker push hcr.io/automated-testing/hot-potato:${{ env.GitVersion_MajorMinorPatch }}
        docker tag hcr.io/automated-testing/hot-potato:${{ env.GitVersion_MajorMinorPatch }} hcr.io/automated-testing/hot-potato:latest
        docker push hcr.io/automated-testing/hot-potato:latest

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-reports
        path: ./test/coverage/*.xml

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test/results/*.xml

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ success() && env.isMaster == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        release_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        draft: false
        prerelease: false
